version: '3.8'

services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - pizzaria-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - pizzaria-network

  estoque-service:
    build:
      context: ./estoque-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - pizzaria-network

  pedidos-service:
    build:
      context: ./pedidos-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=engsoft2
      - SPRING_RABBITMQ_PASSWORD=engsoft2
    depends_on:
      - eureka-server
      - estoque-service
      - rabbitmq
    networks:
      - pizzaria-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=engsoft2
      - RABBITMQ_DEFAULT_PASS=engsoft2
    networks:
      - pizzaria-network

  entrega-service:
    build:
      context: ./entrega-service
      dockerfile: Dockerfile
    # ports:
    #   - "8083:8083" 
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=engsoft2
      - SPRING_RABBITMQ_PASSWORD=engsoft2
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - pizzaria-network

networks:
  pizzaria-network:
    driver: bridge